spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_management_with_jwt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
